# my global config
global:
  scrape_interval: 5m
  evaluation_interval: 1m

  external_labels:
    monitor: "cloudf"

rule_files:
  - "alert.rules"
  - "uptime.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - https://apim-iow-apimanagement.azure-api.net/ldes/devices/devices-by-time
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  - job_name: "ldes-conformance"
    metrics_path: /probe
    static_configs:
      - targets:
          - https://apim-iow-apimanagement.azure-api.net/ldes/devices/devices-by-time
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: conformance-exporter:8000
